### ISSUE TITLE
关于答题

### ISSUE THREAD

**Issue by jiaton** [XiangyuTang/LearnChinaHelper#1]
可以分为选择和填空
选择比较简单
1. 判断选项个数和空格个数是否相等 相等则全选
2. 否则查看提示并获取提示文本，判断每个选项是否在文本中，如是则选择该选项。

填空题
1. 根据控件层级获取空格个数
2. 获取空格周围字符
3. 查看提示并获取文本
4. 根据空格周围字符进行正则匹配
5. 检查匹配到的答案是否符合空格个数
6. 填写答案

**Comment by XiangyuTang** [comment]
感谢你的建议，我正在开发答题模块，我会考虑的

**Comment by jiaton** [comment]
> 感谢你的建议，我正在开发答题模块，我会考虑的

哈哈哈 开发的很快啊
