### ISSUE TITLE
关于辅助功能

### ISSUE THREAD

**Issue by GH6324** [XiangyuTang/LearnChinaHelper#10]
希望大佬可以开放用root权限来开启辅助功能，这样就不用每次都去设置里打开了

**Comment by XiangyuTang** [comment]
辅助功能似乎是安卓7-8左右的，我是基于无需root的特点开发的，所以暂时不打算考虑为辅助功能单独做开发。另一方面我的手机是可直接一次打开无障碍服务的，没有带辅助功能的手机来做测试，所以暂时也开发不了，望谅解哈~

**Comment by GH6324** [comment]
每次打开软件都会申请root权限。。

**Comment by XiangyuTang** [comment]
你的手机是什么型号的，安卓版本是多少，一般只需要打开无障碍服务或者辅助功能（安卓版本较低的手机），root应该不需要吧

**Comment by fengzhishang1314** [comment]
你的手机安卓版本太低了所以需要root，7.0以上就不用了！
