### ISSUE TITLE
视听时长任务优化

### ISSUE THREAD

**Issue by jisu20162** [XiangyuTang/LearnChinaHelper#11]
视听时长任务能优化下，别家脚本视听时长任务是在完成文章阅读时长的同时后台收听本地广播，完成阅读时长任务后再获取视听时长任务的剩余任务数继续，这样就可以节约一部分时间。这样有个问题就是如果打开的是视频文章，会打断视听时长任务，需重新去本地打开广播。还有做每个文章阅读数量任务和视听任务数量的时间能不能调长点，比如15秒，现有时间有点短，会出现看完不计数的情况，导致循环做任务。

**Comment by XiangyuTang** [comment]
已收到反馈，我想过这种办法，目前这样做的原因是降低任务之间的耦合度利于开发，之后会考虑用户在选择同时做两个时长任务后的时间优化。第二个你说的时间调长一点有利有弊，如果某篇文章用户之前看过，那么将不作为有效文章，同样不会增加积分，所以那15秒仅相当于对阅读时长任务时间累加有帮助，8秒时间足够对一篇没有看过的文章增加积分，返回后积分没变化的原因一是网络延迟，二是该篇文章之前阅读过，不算有效文章。
