### ISSUE TITLE
关于视听学习的优化建议

### ISSUE THREAD

**Issue by wonke** [XiangyuTang/LearnChinaHelper#13]
大佬辛苦了！您的处理逻辑写的很缜密！
视听学习默认界面-第一频道，每日更新的视频数量较少，容易产生观看旧视频不得分。联播频道每日更新的视频数量很多，建议切到此处完成视频任务。

**Comment by wonke** [comment]
执行收藏任务不取消收藏的话，可以方便下次识别是否是新文章。不然重复收藏旧文章拿不到积分。

**Comment by XiangyuTang** [comment]
谢谢你的支持和鼓励！我已收到反馈，针对第一条建议，我看了下联播频道的内容，目前只有3.28的内容，3.29的内容暂未更新，并且很快我就滑到了底线，这样将会对完成视听学习任务以及视听时长任务有很大的隐患，用户可能在昨日已经刷完了视频导致今日翻到了底线没有视频可刷。如果这时再跳转到其他频道，就会显得多此一举并且会增加较大的代码工作量。针对第二条建议，之前我的处理逻辑是收藏后不取消，听取了网友的建议后，我将收藏和评论擦除了痕迹，经过几天的测试，暂未发现收藏后再取消收藏会导致当日收藏积分无法得满的问题。

**Comment by XiangyuTang** [comment]
如果之后发现了收藏后取消收藏，导致第二天的收藏任务无法得到积分，我会将这个逻辑改回去，还是感谢你的建议，希望给个star鼓励！
