### ISSUE TITLE
感谢大神，订阅，每周答题和专项答题出错

### ISSUE THREAD

**Issue by 85524365** [XiangyuTang/LearnChinaHelper#14]
感谢大神，订阅，每周答题和专项答题出错
安卓8.0系统，华为p9
貌似如果订阅、每周和专项答题中的某一个已经做光光、没有了，即使出现“你已经看到我的底限了”，但是软件还在继续往下滑，然后卡住不动了。

**Comment by XiangyuTang** [comment]
感谢你的反馈，请问你是否使用的强国助手最新版本，我尝试过优化这种边界情况

**Comment by XiangyuTang** [comment]
如果你使用的是助手2.0.7版本，应该不会再出现类似的情况，如果依然出现，如果不介意你可以留下的你qq或者上传一下失败的运行悬浮窗日志截图，我看看是卡在什么地方，详细了解一下情况

**Comment by 85524365** [comment]
我用的是2.0.5的，
感激大神，真是及时雨更新啊，这就下来用新版，请问大神是直接覆盖旧版本安装，还是先卸载旧版再装新版？
我的QQ是85524365,乐意随时效劳。

**Comment by XiangyuTang** [comment]
嗯嗯不用客气，如果可以帮忙点一个star就行~建议先卸载原版本，再安装新版本，也请及时留意最新版的发布~

**Comment by 85524365** [comment]
第一批star watching的，嘿嘿😁
