### ISSUE TITLE
建议增加随机延时，减少机器人特征

### ISSUE THREAD

**Issue by DrMewo** [XiangyuTang/LearnChinaHelper#15]
文章 视频 及答题的时间可以加上一个随机时长会更加安全，希望能考虑一下

**Comment by DrMewo** [comment]
另外，答题出现视频会回答“请观看”

**Comment by XiangyuTang** [comment]
随机时长建议会纳入后期考虑中，感谢你的反馈。视频答题回答的内容仅限于“请观看视频”几个字是目前没有办法的办法，因为无法提取到答案。

**Comment by XiangyuTang** [comment]
答题部分难免会遇到部分控件特殊的题或是诸如判断或者视频题型，导致无法抓取控件或者答案内容，出现答错的情况，所以答题有时候答错是不可避免的正常现象。

**Comment by 85524365** [comment]
> 答题部分难免会遇到部分控件特殊的题或是诸如判断或者视频题型，导致无法抓取控件或者答案内容，出现答错的情况，所以答题有时候答错是不可避免的正常现象。

感恩大神。建议把视频答案建个简单题库，毕竟题量少，网友们可以搜集提供
