### ISSUE TITLE
模拟器使用问题反馈

### ISSUE THREAD

**Issue by massger** [XiangyuTang/LearnChinaHelper#4]
![QQ截图20200326211040](https://user-images.githubusercontent.com/27893737/77650463-7ff15c80-6fa6-11ea-9340-c25cc83a92aa.jpg)

**Comment by XiangyuTang** [comment]
这个情况是网络原因造成的，多重启几次试一试，如果一直都是重启任务失败，可能是模拟器的原因，因为软件运行环境需要一定条件，如安卓7以上，其他环境要求可见文档说明。如果模拟器能通过测试或者无法通过测试，欢迎将结果反馈给我！


| |
唐翔宇
|
|
tangxy_01@163.com
|
签名由网易邮箱大师定制
在2020年3月26日 21:13，massger<notifications@github.com> 写道：

**Comment by massger** [comment]
![image](https://user-images.githubusercontent.com/27893737/77720683-938ed880-7023-11ea-921d-e8346b099af8.png)

**Comment by XiangyuTang** [comment]
那应该是不能用模拟器，我认为是可能是安卓系统限制的原因

**Comment by martincccc1992** [comment]
![TIM截图20200327202242](https://user-images.githubusercontent.com/38815018/77755711-c4ddc780-7068-11ea-8ffd-099fb6f925a2.png)
 木木模拟器反馈。。看来应该是不能用模拟器了
