### ISSUE TITLE
Proposal: 增加 重新搜索hint等待时间

### ISSUE THREAD

**Issue by jiaton** [XiangyuTang/LearnChinaHelper#5]
不同手机动画时间可能不同，每次打开hint需要一段时间才能加载完成，如果一次没获取到的话，重新搜索提示时可以增加等待时间或findOnce超时时间。

**Comment by XiangyuTang** [comment]
嗯嗯，这个重新获取提示比较恼人，包括我自己在测试的时候也会遇到多次获取提示的情况，后期会考虑尝试一下这种办法，谢谢反馈！


| |
唐翔宇
|
|
tangxy_01@163.com
|
签名由网易邮箱大师定制
在2020年3月27日 08:49，dalao<notifications@github.com> 写道：

不同手机动画时间可能不同，每次打开hint需要一段时间才能加载完成，如果一次没获取到的话，重新搜索提示时可以增加等待时间或findOnce超时时间。

**Comment by XiangyuTang** [comment]
我今天用正则匹配来找desc不为空的控件试了一下，效果不好，还是用原来的方法比较可靠。
