### ISSUE TITLE
多选题空数和选项数相同情况下的优化

### ISSUE THREAD

**Issue by jiaton** [XiangyuTang/LearnChinaHelper#6]
多选题空格数和选项个数相同时可以不搜索直接全选（很多题目都是这种情况）。
可以用如下思路实现：
```js
var question = className("android.view.View").descMatches(".*。").findOnce()
questionText = question.desc()
var reg = /\S\s+(?=\S)/g;
toastLog(questionText.match(reg).length)
var blankCnt = questionText.match(reg).length //空格个数

if (className("android.widget.ListView").findOnce().children().length==blankCnt){
            className("android.widget.ListView").findOnce().children().forEach(function(child) {
                child.child(0).child(1).click();
            });
        }
```

**Comment by XiangyuTang** [comment]
好的，我已收到反馈，之后会尝试一下这个方案


| |
唐翔宇
|
|
tangxy_01@163.com
|
签名由网易邮箱大师定制
在2020年3月27日 08:55，dalao<notifications@github.com> 写道：

多选题空格数和选项个数相同时可以不搜索直接全选（很多题目都是这种情况）。
可以用如下思路实现：

var question =className("android.view.View").descMatches(".*。").findOnce()

questionText =question.desc()

var reg =/\S\s+(?=\S)/g;

toastLog(questionText.match(reg).length)

var blankCnt =questionText.match(reg).length//空格个数if (className("android.widget.ListView").findOnce().children().length==blankCnt){

            className("android.widget.ListView").findOnce().children().forEach(function(child) {

                child.child(0).child(1).click();

            });

        }
