### ISSUE TITLE
非常感谢大佬发布的助手，不知能否单把软件和源文件发一个包。。。要不然每次更新都要下载200多兆，内网不行啊

### ISSUE THREAD

**Issue by fengzhishang1314** [XiangyuTang/LearnChinaHelper#8]

**Comment by XiangyuTang** [comment]
你是指每次pull下来吗，如果仅需要软件和源代码，可以只下载和文件夹同层的强国助手vx.x.x.apk和AutoLearnChina.js就可以了，历史版本文件夹和Images可能比较大，但是都没啥用

**Comment by fengzhishang1314** [comment]
谢谢大佬，每次我都是下载整个的...不会   “只下载和文件夹同层的强国助手vx.x.x.apk和AutoLearnChina.js”

**Comment by fengzhishang1314** [comment]
非常感谢！

**Comment by XiangyuTang** [comment]
嗯嗯，我刚刚结合了你的需求，利用github的release发布了新版本，以后你可以去release下载js和apk文件

**Comment by fengzhishang1314** [comment]
非常感谢！！谢谢大佬！

**Comment by 85524365** [comment]
> 嗯嗯，我刚刚结合了你的需求，利用github的release发布了新版本，以后你可以去release下载js和apk文件

感恩感谢摩拜大神，请问安装新版本APK，是直接安装，还是先把旧版本卸载再安装？

**Comment by XiangyuTang** [comment]
最好卸载旧版本后再安装新版本，我是这样做的
